#!/usr/bin/env bash
# Ignore shellcheck case SC2086
# Display info about subdomains
# Usage: ./0-world_wide_web <domain> [<subdomain>]

domain_info () {
	info_line = $(dig "$2"."$1" | grep -A1 "ANSWER SECTION:" | tail -1)
	echo "$2 $info_line" | awk '{print "The subdomain " $1 " is a " $5 " record and points to " $6}'
}

if [ "$#" == 1 ]
then
	domain_info "$1" "www"
	domain_info "$1" "lb-01"
	domain_info "$1" "web-01"
	domain_info "$1" "web-02"
elif [ "$#" == 2 ]
then
	domain_info "$2" "$1"
fi
