#!/usr/bin/env bash
#Install nginx on your web-01 server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page)
# using curl, it must return a page that contains the string Hello World!

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
