#!/usr/bin/env bash
# install nginx and adjust default homepage
# add redirection
#Configure your Nginx server so that /redirect_me is redirecting to another page.
#The redirection must be a “301 Moved Permanently”

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chmod -R 755 /var/www
echo "Hello World!" > /var/www/html/index.nginx-debian.html
# ERR_MSG="Ceci n'est pas une page\n"
SERVER_CONFIG=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.hml index.nginx-debian.html;
	error_page 404 /404.html;
	server_name _;
	location / {
		try_files $uri $uri/ =404;
		error_page 404 /404.html;
	}
	location /redirect_me{
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
	location /404.html{
		root /var/www/error;
		index 404.html;
	}
}"

echo -e "$SERVER_CONFIG" > /etc/nginx/sites-available/default
sudo service nginx start
