#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
sudo apt-get -y install haproxy

# configure lb by editing haproxy cfg file
DOMAIN_NAME='thebee.tech'
INIT_FILE='/etc/default/haproxy'
CONFIG_FILE='/etc/haproxy/haproxy.cfg'
STUDENT_ID='56457'
HAPROXY_LB_CONFIG=\
"
frontend $DOMAIN_NAME-frontend
	bind *:80
	mode http
	default_backend $DOMAIN_NAME-backend
backend $DOMAIN_NAME-backend
	balance roundrobin
	server $STUDENT_ID-web-01 54.236.56.204 check
	server $STUDENT_ID-web-02 54.197.112.57:80 check
"
echo "$HAPROXY_LB_CONFIG" | sudo tee -a $CONFIG_FILE

# enable haproxy to be started by init script
echo "ENABLED=1" | sudo tee -a $INIT_FILE

sudo service haproxy restart
